#include <RWStepElement_RWAnalysisItemWithinRepresentation.hxx>
#include <RWStepElement_RWCurve3dElementDescriptor.hxx>
#include <RWStepElement_RWCurveElementEndReleasePacket.hxx>
#include <RWStepElement_RWCurveElementSectionDefinition.hxx>
#include <RWStepElement_RWCurveElementSectionDerivedDefinitions.hxx>
#include <RWStepElement_RWElementDescriptor.hxx>
#include <RWStepElement_RWElementMaterial.hxx>
#include <RWStepElement_RWSurface3dElementDescriptor.hxx>
#include <RWStepElement_RWSurfaceElementProperty.hxx>
#include <RWStepElement_RWSurfaceSection.hxx>
#include <RWStepElement_RWSurfaceSectionField.hxx>
#include <RWStepElement_RWSurfaceSectionFieldConstant.hxx>
#include <RWStepElement_RWSurfaceSectionFieldVarying.hxx>
#include <RWStepElement_RWUniformSurfaceSection.hxx>
#include <RWStepElement_RWVolume3dElementDescriptor.hxx>
#include <RWStepFEA_RWAlignedCurve3dElementCoordinateSystem.hxx>
#include <RWStepFEA_RWAlignedSurface3dElementCoordinateSystem.hxx>
#include <RWStepFEA_RWArbitraryVolume3dElementCoordinateSystem.hxx>
#include <RWStepFEA_RWConstantSurface3dElementCoordinateSystem.hxx>
#include <RWStepFEA_RWCurve3dElementProperty.hxx>
#include <RWStepFEA_RWCurve3dElementRepresentation.hxx>
#include <RWStepFEA_RWCurveElementEndOffset.hxx>
#include <RWStepFEA_RWCurveElementEndRelease.hxx>
#include <RWStepFEA_RWCurveElementInterval.hxx>
#include <RWStepFEA_RWCurveElementIntervalConstant.hxx>
#include <RWStepFEA_RWCurveElementIntervalLinearlyVarying.hxx>
#include <RWStepFEA_RWCurveElementLocation.hxx>
#include <RWStepFEA_RWDummyNode.hxx>
#include <RWStepFEA_RWElementGeometricRelationship.hxx>
#include <RWStepFEA_RWElementGroup.hxx>
#include <RWStepFEA_RWElementRepresentation.hxx>
#include <RWStepFEA_RWFeaAreaDensity.hxx>
#include <RWStepFEA_RWFeaAxis2Placement3d.hxx>
#include <RWStepFEA_RWFeaCurveSectionGeometricRelationship.hxx>
#include <RWStepFEA_RWFeaGroup.hxx>
#include <RWStepFEA_RWFeaLinearElasticity.hxx>
#include <RWStepFEA_RWFeaMassDensity.hxx>
#include <RWStepFEA_RWFeaMaterialPropertyRepresentation.hxx>
#include <RWStepFEA_RWFeaMaterialPropertyRepresentationItem.hxx>
#include <RWStepFEA_RWFeaModel.hxx>
#include <RWStepFEA_RWFeaModel3d.hxx>
#include <RWStepFEA_RWFeaModelDefinition.hxx>
#include <RWStepFEA_RWFeaMoistureAbsorption.hxx>
#include <RWStepFEA_RWFeaParametricPoint.hxx>
#include <RWStepFEA_RWFeaRepresentationItem.hxx>
#include <RWStepFEA_RWFeaSecantCoefficientOfLinearThermalExpansion.hxx>
#include <RWStepFEA_RWFeaShellBendingStiffness.hxx>
#include <RWStepFEA_RWFeaShellMembraneBendingCouplingStiffness.hxx>
#include <RWStepFEA_RWFeaShellMembraneStiffness.hxx>
#include <RWStepFEA_RWFeaShellShearStiffness.hxx>
#include <RWStepFEA_RWFeaSurfaceSectionGeometricRelationship.hxx>
#include <RWStepFEA_RWFeaTangentialCoefficientOfLinearThermalExpansion.hxx>
#include <RWStepFEA_RWFreedomAndCoefficient.hxx>
#include <RWStepFEA_RWFreedomsList.hxx>
#include <RWStepFEA_RWGeometricNode.hxx>
#include <RWStepFEA_RWNode.hxx>
#include <RWStepFEA_RWNodeDefinition.hxx>
#include <RWStepFEA_RWNodeGroup.hxx>
#include <RWStepFEA_RWNodeRepresentation.hxx>
#include <RWStepFEA_RWNodeSet.hxx>
#include <RWStepFEA_RWNodeWithSolutionCoordinateSystem.hxx>
#include <RWStepFEA_RWNodeWithVector.hxx>
#include <RWStepFEA_RWParametricCurve3dElementCoordinateDirection.hxx>
#include <RWStepFEA_RWParametricCurve3dElementCoordinateSystem.hxx>
#include <RWStepFEA_RWParametricSurface3dElementCoordinateSystem.hxx>
#include <RWStepFEA_RWSurface3dElementRepresentation.hxx>
#include <RWStepFEA_RWVolume3dElementRepresentation.hxx>
#include <StepElement_AnalysisItemWithinRepresentation.hxx>
#include <StepElement_Curve3dElementDescriptor.hxx>
#include <StepElement_CurveEdge.hxx>
#include <StepElement_CurveElementEndReleasePacket.hxx>
#include <StepElement_CurveElementFreedom.hxx>
#include <StepElement_CurveElementFreedomMember.hxx>
#include <StepElement_CurveElementPurpose.hxx>
#include <StepElement_CurveElementPurposeMember.hxx>
#include <StepElement_CurveElementSectionDefinition.hxx>
#include <StepElement_CurveElementSectionDerivedDefinitions.hxx>
#include <StepElement_Element2dShape.hxx>
#include <StepElement_ElementAspect.hxx>
#include <StepElement_ElementAspectMember.hxx>
#include <StepElement_ElementDescriptor.hxx>
#include <StepElement_ElementMaterial.hxx>
#include <StepElement_ElementOrder.hxx>
#include <StepElement_ElementVolume.hxx>
#include <StepElement_EnumeratedCurveElementFreedom.hxx>
#include <StepElement_EnumeratedCurveElementPurpose.hxx>
#include <StepElement_EnumeratedSurfaceElementPurpose.hxx>
#include <StepElement_EnumeratedVolumeElementPurpose.hxx>
#include <StepElement_HSequenceOfCurveElementPurposeMember.hxx>
#include <StepElement_HSequenceOfCurveElementSectionDefinition.hxx>
#include <StepElement_HSequenceOfElementMaterial.hxx>
#include <StepElement_HSequenceOfSurfaceElementPurposeMember.hxx>
#include <StepElement_MeasureOrUnspecifiedValue.hxx>
#include <StepElement_MeasureOrUnspecifiedValueMember.hxx>
#include <StepElement_SequenceOfCurveElementPurposeMember.hxx>
#include <StepElement_SequenceOfCurveElementSectionDefinition.hxx>
#include <StepElement_SequenceOfElementMaterial.hxx>
#include <StepElement_SequenceOfSurfaceElementPurposeMember.hxx>
#include <StepElement_Surface3dElementDescriptor.hxx>
#include <StepElement_SurfaceElementProperty.hxx>
#include <StepElement_SurfaceElementPurpose.hxx>
#include <StepElement_SurfaceElementPurposeMember.hxx>
#include <StepElement_SurfaceSection.hxx>
#include <StepElement_SurfaceSectionField.hxx>
#include <StepElement_SurfaceSectionFieldConstant.hxx>
#include <StepElement_SurfaceSectionFieldVarying.hxx>
#include <StepElement_UniformSurfaceSection.hxx>
#include <StepElement_UnspecifiedValue.hxx>
#include <StepElement_Volume3dElementDescriptor.hxx>
#include <StepElement_Volume3dElementShape.hxx>
#include <StepElement_VolumeElementPurpose.hxx>
#include <StepElement_VolumeElementPurposeMember.hxx>
#include <StepFEA_AlignedCurve3dElementCoordinateSystem.hxx>
#include <StepFEA_AlignedSurface3dElementCoordinateSystem.hxx>
#include <StepFEA_ArbitraryVolume3dElementCoordinateSystem.hxx>
#include <StepFEA_ConstantSurface3dElementCoordinateSystem.hxx>
#include <StepFEA_CoordinateSystemType.hxx>
#include <StepFEA_Curve3dElementProperty.hxx>
#include <StepFEA_Curve3dElementRepresentation.hxx>
#include <StepFEA_CurveEdge.hxx>
#include <StepFEA_CurveElementEndCoordinateSystem.hxx>
#include <StepFEA_CurveElementEndOffset.hxx>
#include <StepFEA_CurveElementEndRelease.hxx>
#include <StepFEA_CurveElementInterval.hxx>
#include <StepFEA_CurveElementIntervalConstant.hxx>
#include <StepFEA_CurveElementIntervalLinearlyVarying.hxx>
#include <StepFEA_CurveElementLocation.hxx>
#include <StepFEA_DegreeOfFreedom.hxx>
#include <StepFEA_DegreeOfFreedomMember.hxx>
#include <StepFEA_DummyNode.hxx>
#include <StepFEA_ElementGeometricRelationship.hxx>
#include <StepFEA_ElementGroup.hxx>
#include <StepFEA_ElementOrElementGroup.hxx>
#include <StepFEA_ElementRepresentation.hxx>
#include <StepFEA_ElementVolume.hxx>
#include <StepFEA_EnumeratedDegreeOfFreedom.hxx>
#include <StepFEA_FeaAreaDensity.hxx>
#include <StepFEA_FeaAxis2Placement3d.hxx>
#include <StepFEA_FeaCurveSectionGeometricRelationship.hxx>
#include <StepFEA_FeaGroup.hxx>
#include <StepFEA_FeaLinearElasticity.hxx>
#include <StepFEA_FeaMassDensity.hxx>
#include <StepFEA_FeaMaterialPropertyRepresentation.hxx>
#include <StepFEA_FeaMaterialPropertyRepresentationItem.hxx>
#include <StepFEA_FeaModel.hxx>
#include <StepFEA_FeaModel3d.hxx>
#include <StepFEA_FeaModelDefinition.hxx>
#include <StepFEA_FeaMoistureAbsorption.hxx>
#include <StepFEA_FeaParametricPoint.hxx>
#include <StepFEA_FeaRepresentationItem.hxx>
#include <StepFEA_FeaSecantCoefficientOfLinearThermalExpansion.hxx>
#include <StepFEA_FeaShellBendingStiffness.hxx>
#include <StepFEA_FeaShellMembraneBendingCouplingStiffness.hxx>
#include <StepFEA_FeaShellMembraneStiffness.hxx>
#include <StepFEA_FeaShellShearStiffness.hxx>
#include <StepFEA_FeaSurfaceSectionGeometricRelationship.hxx>
#include <StepFEA_FeaTangentialCoefficientOfLinearThermalExpansion.hxx>
#include <StepFEA_FreedomAndCoefficient.hxx>
#include <StepFEA_FreedomsList.hxx>
#include <StepFEA_GeometricNode.hxx>
#include <StepFEA_HSequenceOfCurve3dElementProperty.hxx>
#include <StepFEA_HSequenceOfElementGeometricRelationship.hxx>
#include <StepFEA_HSequenceOfElementRepresentation.hxx>
#include <StepFEA_HSequenceOfNodeRepresentation.hxx>
#include <StepFEA_Node.hxx>
#include <StepFEA_NodeDefinition.hxx>
#include <StepFEA_NodeGroup.hxx>
#include <StepFEA_NodeRepresentation.hxx>
#include <StepFEA_NodeSet.hxx>
#include <StepFEA_NodeWithSolutionCoordinateSystem.hxx>
#include <StepFEA_NodeWithVector.hxx>
#include <StepFEA_ParametricCurve3dElementCoordinateDirection.hxx>
#include <StepFEA_ParametricCurve3dElementCoordinateSystem.hxx>
#include <StepFEA_ParametricSurface3dElementCoordinateSystem.hxx>
#include <StepFEA_SequenceOfCurve3dElementProperty.hxx>
#include <StepFEA_SequenceOfElementGeometricRelationship.hxx>
#include <StepFEA_SequenceOfElementRepresentation.hxx>
#include <StepFEA_SequenceOfNodeRepresentation.hxx>
#include <StepFEA_Surface3dElementRepresentation.hxx>
#include <StepFEA_SymmetricTensor22d.hxx>
#include <StepFEA_SymmetricTensor23d.hxx>
#include <StepFEA_SymmetricTensor23dMember.hxx>
#include <StepFEA_SymmetricTensor42d.hxx>
#include <StepFEA_SymmetricTensor43d.hxx>
#include <StepFEA_SymmetricTensor43dMember.hxx>
#include <StepFEA_UnspecifiedValue.hxx>
#include <StepFEA_Volume3dElementRepresentation.hxx>

#include <../handle_class.h>

DEFINE_HANDLECLASS(StepElement_AnalysisItemWithinRepresentation)
DEFINE_HANDLECLASS(StepElement_Curve3dElementDescriptor)
DEFINE_HANDLECLASS(StepElement_CurveElementEndReleasePacket)
DEFINE_HANDLECLASS(StepElement_CurveElementFreedomMember)
DEFINE_HANDLECLASS(StepElement_CurveElementPurposeMember)
DEFINE_HANDLECLASS(StepElement_CurveElementSectionDefinition)
DEFINE_HANDLECLASS(StepElement_CurveElementSectionDerivedDefinitions)
DEFINE_HANDLECLASS(StepElement_ElementAspectMember)
DEFINE_HANDLECLASS(StepElement_ElementDescriptor)
DEFINE_HANDLECLASS(StepElement_ElementMaterial)
DEFINE_HANDLECLASS(StepElement_MeasureOrUnspecifiedValueMember)
DEFINE_HANDLECLASS(StepElement_Surface3dElementDescriptor)
DEFINE_HANDLECLASS(StepElement_SurfaceElementProperty)
DEFINE_HANDLECLASS(StepElement_SurfaceElementPurposeMember)
DEFINE_HANDLECLASS(StepElement_SurfaceSection)
DEFINE_HANDLECLASS(StepElement_SurfaceSectionField)
DEFINE_HANDLECLASS(StepElement_SurfaceSectionFieldConstant)
DEFINE_HANDLECLASS(StepElement_SurfaceSectionFieldVarying)
DEFINE_HANDLECLASS(StepElement_UniformSurfaceSection)
DEFINE_HANDLECLASS(StepElement_Volume3dElementDescriptor)
DEFINE_HANDLECLASS(StepElement_VolumeElementPurposeMember)
DEFINE_HANDLECLASS(StepFEA_AlignedCurve3dElementCoordinateSystem)
DEFINE_HANDLECLASS(StepFEA_AlignedSurface3dElementCoordinateSystem)
DEFINE_HANDLECLASS(StepFEA_ArbitraryVolume3dElementCoordinateSystem)
DEFINE_HANDLECLASS(StepFEA_ConstantSurface3dElementCoordinateSystem)
DEFINE_HANDLECLASS(StepFEA_Curve3dElementProperty)
DEFINE_HANDLECLASS(StepFEA_Curve3dElementRepresentation)
DEFINE_HANDLECLASS(StepFEA_CurveElementEndOffset)
DEFINE_HANDLECLASS(StepFEA_CurveElementEndRelease)
DEFINE_HANDLECLASS(StepFEA_CurveElementInterval)
DEFINE_HANDLECLASS(StepFEA_CurveElementIntervalConstant)
DEFINE_HANDLECLASS(StepFEA_CurveElementIntervalLinearlyVarying)
DEFINE_HANDLECLASS(StepFEA_CurveElementLocation)
DEFINE_HANDLECLASS(StepFEA_DegreeOfFreedomMember)
DEFINE_HANDLECLASS(StepFEA_DummyNode)
DEFINE_HANDLECLASS(StepFEA_ElementGeometricRelationship)
DEFINE_HANDLECLASS(StepFEA_ElementGroup)
DEFINE_HANDLECLASS(StepFEA_ElementRepresentation)
DEFINE_HANDLECLASS(StepFEA_FeaAreaDensity)
DEFINE_HANDLECLASS(StepFEA_FeaAxis2Placement3d)
DEFINE_HANDLECLASS(StepFEA_FeaCurveSectionGeometricRelationship)
DEFINE_HANDLECLASS(StepFEA_FeaGroup)
DEFINE_HANDLECLASS(StepFEA_FeaLinearElasticity)
DEFINE_HANDLECLASS(StepFEA_FeaMassDensity)
DEFINE_HANDLECLASS(StepFEA_FeaMaterialPropertyRepresentation)
DEFINE_HANDLECLASS(StepFEA_FeaMaterialPropertyRepresentationItem)
DEFINE_HANDLECLASS(StepFEA_FeaModel)
DEFINE_HANDLECLASS(StepFEA_FeaModel3d)
DEFINE_HANDLECLASS(StepFEA_FeaModelDefinition)
DEFINE_HANDLECLASS(StepFEA_FeaMoistureAbsorption)
DEFINE_HANDLECLASS(StepFEA_FeaParametricPoint)
DEFINE_HANDLECLASS(StepFEA_FeaRepresentationItem)
DEFINE_HANDLECLASS(StepFEA_FeaSecantCoefficientOfLinearThermalExpansion)
DEFINE_HANDLECLASS(StepFEA_FeaShellBendingStiffness)
DEFINE_HANDLECLASS(StepFEA_FeaShellMembraneBendingCouplingStiffness)
DEFINE_HANDLECLASS(StepFEA_FeaShellMembraneStiffness)
DEFINE_HANDLECLASS(StepFEA_FeaShellShearStiffness)
DEFINE_HANDLECLASS(StepFEA_FeaSurfaceSectionGeometricRelationship)
DEFINE_HANDLECLASS(StepFEA_FeaTangentialCoefficientOfLinearThermalExpansion)
DEFINE_HANDLECLASS(StepFEA_FreedomAndCoefficient)
DEFINE_HANDLECLASS(StepFEA_FreedomsList)
DEFINE_HANDLECLASS(StepFEA_GeometricNode)
DEFINE_HANDLECLASS(StepFEA_Node)
DEFINE_HANDLECLASS(StepFEA_NodeDefinition)
DEFINE_HANDLECLASS(StepFEA_NodeGroup)
DEFINE_HANDLECLASS(StepFEA_NodeRepresentation)
DEFINE_HANDLECLASS(StepFEA_NodeSet)
DEFINE_HANDLECLASS(StepFEA_NodeWithSolutionCoordinateSystem)
DEFINE_HANDLECLASS(StepFEA_NodeWithVector)
DEFINE_HANDLECLASS(StepFEA_ParametricCurve3dElementCoordinateDirection)
DEFINE_HANDLECLASS(StepFEA_ParametricCurve3dElementCoordinateSystem)
DEFINE_HANDLECLASS(StepFEA_ParametricSurface3dElementCoordinateSystem)
DEFINE_HANDLECLASS(StepFEA_Surface3dElementRepresentation)
DEFINE_HANDLECLASS(StepFEA_SymmetricTensor23dMember)
DEFINE_HANDLECLASS(StepFEA_SymmetricTensor43dMember)
DEFINE_HANDLECLASS(StepFEA_Volume3dElementRepresentation)

